from dydx3.constants import API_HOST_GOERLI
from decouple import config

TOKEN_FACTOR_10 = ["XLM-USD","DOGE-USD","TRON-USD", "ENJ-USD", "SNX-USD", "MATIC-USD", "NEAR-USD", "UNI-USD",
                    "ATOM-USD", "ADA-USD", "YFI-USD", "XTZ-USD"]

ABORT_ALL_POSITIONS = True

FIND_COINTEGRATED = True

PLACE_TRADES = True

MANAGE_EXITS = True

RESOLUTION = "1HOUR"

WINDOW = 21

MAX_HALF_LIFE = 24

ZSCORE_THRESH = 1.5

USD_PER_TRADE = 50

USD_MIN_COLLATERAL = 1900

CLOSE_AT_ZSCORE_CROSS = True

ETHEREUM_ADDRESS = '0x4ae7B6A7f864218c7bD336597DFc39475C10e84d'

HOST = API_HOST_GOERLI

HTTP_PROVIDER = 'https://eth-goerli.g.alchemy.com/v2/Db3IrxKuwkxQw8kUiFl-QaCGrasxi2HN'

ETH_PRIVATE_KEY = config('ETH_PRIVATE_KEY')
STARK_PRIVATE_KEY = config('STARK_PRIVATE_KEY')
DYDX_API_KEY = config('DYDX_API_KEY')
DYDX_API_SECRET = config('DYDX_API_SECRET')
DYDX_API_PASSPHRASE = config('DYDX_API_PASSPHRASE')

TELEGRAM_TOKEN = config('TELEGRAM_TOKEN')
TELEGRAM_CHAT_ID = config('TELEGRAM_CHAT_ID')

